### ISSUE TITLE
V2 not compatible with crosswalk

### ISSUE THREAD

**Issue by bringitup** [mapsplugin/v2.0-demo#13]
Tested the v2 with crosswalk 21, the map is not showing (working fine if I removed cordova-plugin-crosswalk-webview)

Here is the trace from the android debugger
_10-28 15:16:06.319: E/chromium(29886): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
10-28 15:16:06.365: E/chromium(29886): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
10-28 15:16:06.585: W/PluginManager(29886): THREAD WARNING: exec() call to CordovaGoogleMaps.putHtmlElements blocked the main thread for 21ms. Plugin should use CordovaInterface.getThreadPool().
10-28 15:16:07.002: W/PluginManager(29886): THREAD WARNING: exec() call to CordovaGoogleMaps.putHtmlElements blocked the main thread for 44ms. Plugin should use CordovaInterface.getThreadPool().
10-28 15:16:07.177: W/f(29886): Suppressed StrictMode policy violation: StrictModeDiskWriteViolation
10-28 15:16:07.179: W/f(29886): Suppressed StrictMode policy violation: StrictModeDiskReadViolation
10-28 15:16:07.207: W/cr_BindingManager(29886): Cannot call determinedVisibility() - never saw a connection for the pid: 29886
10-28 15:16:08.505: W/ctxmgr(1261): [ContextSpecificAclFactory]LocationConsent failed, ULR opt-in status is: false_

Also tested with crosswalk 22-beta with same result
Tested with cordova-android v5.2.2 and v6.0.0
(works fine for iOS)

Thanks for this plugin

**Comment by wf9a5m75** [comment]
Not compatible with crosswalk currently.

**Comment by eg271** [comment]
Any update on when this might be ready? Thanks

**Comment by Fayozjon** [comment]
Need crosswalk too.. ping @wf9a5m75

**Comment by gbelmm** [comment]
+1 please

**Comment by banterstudios** [comment]
+1

**Comment by baltrap33** [comment]
👍

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/Installation/crosswalk/README.md
