### ISSUE TITLE
animateCamera always zooms

### ISSUE THREAD

**Issue by samedii** [mapsplugin/v2.0-demo#14]
console.log('zoom: ' + worldMap.getCameraZoom()); //"zoom: 15"
    
    worldMap.animateCamera({
        target: latLng,
        zoom: 15 //this can be removed, does not matter what it is set to
    }, () => {
        console.log('zoom: ' + worldMap.getCameraZoom()); //"zoom: 21"
    });

If animateCamera is replaced by moveCamera it also doesn't work since they use the same logic. However, setCameraTarget(latLng) works.

I will look through the code and try to see what's going on

**Comment by wf9a5m75** [comment]
Thank you for moving this issue.
Is the latLng just `{lat: ..., lng: ...}` or `Array.<{lat: ..., lng: ...}>`?

**Comment by samedii** [comment]
Just {lat: number, lng: number}. Got an idea?

**Comment by wf9a5m75** [comment]
I need to focus on my real job right now.
But please try to comment out these lines, and test your code.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/android/plugin/google/maps/PluginMap.java#L1356-L1389

**Comment by samedii** [comment]
Commenting that out did not change anything.

This is original problematic code.

    if ("org.json.JSONArray".equals(targetClass.getName())) {
        JSONArray points = cameraPos.getJSONArray("target");
        result.cameraBounds = PluginUtil.JSONArray2LatLngBounds(points);
        result.cameraUpdate = CameraUpdateFactory.newLatLngBounds(result.cameraBounds, (int)(result.cameraPadding * density));
    } else {
        latLng = cameraPos.getJSONObject("target");
        builder.target(new LatLng(latLng.getDouble("lat"), latLng.getDouble("lng")));
        newPosition = builder.build();
        result.cameraUpdate = CameraUpdateFactory.newCameraPosition(newPosition);
    }

    cameraPosition.target = common.convertToPositionArray(cameraPosition.target);

I commited a PR changing the java code but you might have a better solution (I would have prefered changing Map.js but didn't dare to since it might break iOS)

**Comment by wf9a5m75** [comment]
Thank you. I fixed the Map.js. Your inspection saved my time.
