### ISSUE TITLE
Preserve current camera position unless otherwise specified

### ISSUE THREAD

**Issue by samedii** [mapsplugin/v2.0-demo#15]
In other words, preserve current tilt, bearing, and zoom if it is not defined in animateCamera/moveCamera.

Would like to change the following line in updateCameraPosition (L1175):

    final CameraPosition.Builder builder = CameraPosition.builder();

To:

    final CameraPosition.Builder builder = CameraPosition.builder(map.getCameraPosition());

But it seems like `map` is not defined. I am not sure how the code works here. Do you have any suggestions how to achieve this behaviour in a good way?

I also tried using `map` like:

    if (cameraPos.has("tilt")) {
        builder.tilt((float) cameraPos.getDouble("tilt"));
    }
    else {
        builder.tilt(map.getCameraPosition().tilt);
    }

but it didn't work for the same reason I think

**Comment by wf9a5m75** [comment]
Although I haven't checked on the iOS code yet, I fixed this issue on the Android code.

Use the [issue_15](https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/issue_15) branch or download the [PluginMap.java](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/issue_15/src/android/plugin/google/maps/PluginMap.java) then replace it.

![capture](https://cloud.githubusercontent.com/assets/167831/20116316/9d9b798c-a5b0-11e6-9a6a-52511c8fd237.gif)

**Comment by samedii** [comment]
Awesome, thanks! I haven't been able to get it to work yet and test it. I've updated to API version 25. It's building now but I get an alert when I open the app. Will try again tomorrow when I get home from work

**Comment by samedii** [comment]
I had some trouble with new updates of android studio breaking everything but finally got it working. Thank you, it fixed it!
