### ISSUE TITLE
Zoom changes at last tick

### ISSUE THREAD

**Issue by samedii** [mapsplugin/v2.0-demo#16]
With the new PR for zoom, animateCamera works but changes zoom at the last millisecond

If it is originally 15, then it changes to 13.572578430175781

                console.log(worldMap.getCameraZoom());
                worldMap.animateCamera({
                    target: latLng,
                    zoom: worldMap.getCameraZoom(),
                    bearing: worldMap.getCameraBearing(),
                    tilt: worldMap.getCameraTilt(),
                    duration: 500
                }, () => {
                    //done
                    console.log(worldMap.getCameraZoom());
                });

If I change the bearing and tilt to nothing then it only changes from, originally: 15, to 14.874504089355469

                console.log(worldMap.getCameraZoom());
                worldMap.animateCamera({
                    target: latLng,
                    zoom: worldMap.getCameraZoom(),
                    //bearing: worldMap.getCameraBearing(),
                    //tilt: worldMap.getCameraTilt(),
                    duration: 500
                }, () => {
                    //done
                    console.log(worldMap.getCameraZoom());
                });

Maybe you know what it is. If not, I will have a look at it when I have time.

Could this be related to padding and the visible region?

**Comment by wf9a5m75** [comment]
>Could this be related to padding and the visible region?

Of course.
And you will learn how I set multiple parameters.

**Comment by samedii** [comment]
Can't see the problem on the latest commit. Did you do something to fix it? However, this might be related to the lag introduced by all the logging? 

I get lots of this:
`D/CordovaWebViewImpl: >>> loadUrl(javascript:cordova.fireDocumentEvent('map_0_847685193115', {evtName:'camera_move', callback:'_onCameraEvent', args: [{"bearing":0,"tilt":60,"zoom":15,"target":{"lat":41.812085971314296,"lng":140.7711847499013}}]}))`

**Comment by wf9a5m75** [comment]
Yes, I updated the multiple_maps branch. I fixed the #15 then merged into the multiple_maps branch.

Regarding of the lots of log are the Cordova problem.
It seems Cordova outputs the url when the native plugin executes `webView.loadUrl(js);`.
I haven't figured out how to disable the log outputting.

**Comment by wf9a5m75** [comment]
Problem is here.
https://github.com/apache/cordova-android/blob/23fd0982b0faa6b7e169c2946eab07930f1f4d16/framework/src/org/apache/cordova/CordovaWebViewImpl.java#L125-L126

**Comment by samedii** [comment]
Okay, good. I'll close this too then :)
