### ISSUE TITLE
Property scrollView not found on object of type UIView

### ISSUE THREAD

**Issue by mrameezraja** [mapsplugin/v2.0-demo#17]
I have installed console, whitelist and wkwebview plugin, but i am getting soo many errors of 'Property scrollView not found on object of type UIView'.

Any help would be highly appreciated.

**Comment by wf9a5m75** [comment]
Please post your error logs.

**Comment by mrameezraja** [comment]
<img width="1552" alt="screen shot 2016-11-08 at 2 09 29 pm" src="https://cloud.githubusercontent.com/assets/8121938/20093018/cb433c64-a54f-11e6-9a14-c8a67c06461d.png">

**Comment by wf9a5m75** [comment]
The multiple_maps branch works with https://github.com/apache/cordova-plugin-wkwebview-engine

Install the above plugin, then you need to define these lines into the config.xml
```
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

After that, `$> cordova build` before opening with Xcode.

**Comment by mrameezraja** [comment]
After i added wkwebview-engine everything works fine. But it is still eating battery and heating up the phone. One thing improved that the app doesn't crash now due to memory leaks.

**Comment by wf9a5m75** [comment]
Please post your error logs (not only screen capture please)

**Comment by mrameezraja** [comment]
Crash Error Log:
<pre>
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x174c4a950> was mutated while being enumerated.'
*** First throw call stack:
(0x18fe081c0 0x18e84055c 0x18fe07c08 0x1000c8190 0x195f44ea8 0x195c8af50 0x18fcf51a4 0x18fcf50a0 0x195c8aa88 0x195f44ea8 0x195c8af50 0x18fcf51a4 0x18fcf50a0 0x195c8aa88 0x195f44ea8 0x195f2d9ac 0x195c55a98 0x195f2d874 0x195f2dbb8 0x19643b020 0x19643e3d4 0x196438720 0x18fdb6278 0x18fdb5bc0 0x18fdb37c0 0x18fce2048 0x191765198 0x195cbc628 0x195cb7360 0x10000fd88 0x18ecc45b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
</pre>

There are no errors i can find for battery consumption issue. But it is eating battery and heating up the phone. Is there anyway i can find the reason for heating and battery consumption?

**Comment by wf9a5m75** [comment]
Thank you, but the crash log is not included everything. I can not figure out where is problem.

The reason of battery consumption is your html has lots of Dom elements (I guess).

Please understand how the plugin recognize all html elements positions.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F#change-4-save-battery-life

When you tap on the app, the plugin checks all Dom positions and size (and other CSS).
If you tap a lot, and there are lots of Dom elements, the plugin has to work a lot.

**Comment by mrameezraja** [comment]
It has 15 (`[self.HTMLNodes count]`) html elements. Are they too much for plugin?

**Comment by wf9a5m75** [comment]
I see. Please share your project with whole project files.

**Comment by wf9a5m75** [comment]
@mrameezraja ping

**Comment by mrameezraja** [comment]
We are going for js api. Thanks @wf9a5m75

**Comment by wf9a5m75** [comment]
ok.
