### ISSUE TITLE
Remove Ground Overlay Crash

### ISSUE THREAD

**Issue by eg271** [mapsplugin/v2.0-demo#19]
Emulator console output:

```
*** Terminating app due to uncaught exception 'GMSThreadException', reason: 'The API method must be called from the main thread'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106e43d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010688edeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106e43cbd +[NSException raise:format:] + 205
	3   CityMeet                            0x0000000102663402 -[GMSOverlay setMap:] + 86
	4   CityMeet                            0x00000001025175c1 __30-[PluginGroundOverlay remove:]_block_invoke + 417
	5   Foundation                          0x0000000106501630 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	6   Foundation                          0x000000010643c805 -[NSBlockOperation main] + 101
	7   Foundation                          0x000000010641f725 -[__NSOperationInternal _start:] + 646
	8   Foundation                          0x000000010641f336 __NSOQSchedule_f + 194
	9   libdispatch.dylib                   0x00000001082873eb _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010826d82c _dispatch_queue_drain + 2215
	11  libdispatch.dylib                   0x000000010826cd4d _dispatch_queue_invoke + 601
	12  libdispatch.dylib                   0x000000010826f996 _dispatch_root_queue_drain + 1420
	13  libdispatch.dylib                   0x000000010826f405 _dispatch_worker_thread3 + 111
	14  libsystem_pthread.dylib             0x00000001085c44de _pthread_wqthread + 1129
	15  libsystem_pthread.dylib             0x00000001085c2341 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by wf9a5m75** [comment]
Oh, sorry. I updated the code.
Please reinstall the plugin.

**Comment by eg271** [comment]
Many thanks for the speedy fix.  There also seems to be an intermittent crash issue with overlay setMap:

*** Terminating app due to uncaught exception 'GMSThreadException', reason: 'The API method must be called from the main thread'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e49034b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010dec821e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e4f9265 +[NSException raise:format:] + 197
	3   CityMeet                            0x0000000108df79c2 -[GMSOverlay setMap:] + 86
	4   CityMeet                            0x0000000108c56a11 __30-[PluginGroundOverlay remove:]_block_invoke + 417
	5   Foundation                          0x000000010d9cc23d __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	6   Foundation                          0x000000010d9cbf1f -[NSBlockOperation main] + 101
	7   Foundation                          0x000000010d9ca61c -[__NSOperationInternal _start:] + 672
	8   Foundation                          0x000000010d9c655f __NSOQSchedule_f + 201
	9   libdispatch.dylib                   0x000000010ecaa0cd _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010ec87e6b _dispatch_queue_serial_drain + 236
	11  libdispatch.dylib                   0x000000010ec88b9f _dispatch_queue_invoke + 1073
	12  libdispatch.dylib                   0x000000010ec8b3b7 _dispatch_root_queue_drain + 720
	13  libdispatch.dylib                   0x000000010ec8b08b _dispatch_worker_thread3 + 123
	14  libsystem_pthread.dylib             0x000000010f0534de _pthread_wqthread + 1129
	15  libsystem_pthread.dylib             0x000000010f051341 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by wf9a5m75** [comment]
Could you provide a sample code?

**Comment by wf9a5m75** [comment]
@eg271 I rechecked the code, but I could not find out where the problem is.
Could you show me an example code?

**Comment by eg271** [comment]
I'm trying to test it again to repeat the error and narrow down the problem but am now having a new issue with the latest version.  It seems to block all input to the entire webview even if not having created a map (layer issue?).  if I remove the plugin I can click and interact with the webview but otherwise it's blocked.  If I create a UI alert from Safari Debugger Console, I can click the OK button however.

**Comment by wf9a5m75** [comment]
Please provide example project using github (or bitbuket).
And video screen record is appriciated.

**Comment by eg271** [comment]
Ok, starting with the loss of input:

eg271/cordova-gmaps-test

Just swap in the index.html & config.xml files into a new blank Cordova project (am using 6.4.0).
The button on the page doesn't work using the #multiple branch but does with v1.

**Comment by wf9a5m75** [comment]
I have no problem at all

<table>
<tr>
<th>Andorid</th>
<th>iOS</th>
</tr>
<tr>
<td>
<img src="https://cloud.githubusercontent.com/assets/167831/20497749/41af5da8-afdf-11e6-93b8-0db0a7b2dd32.gif">
</td>
<td>
<img src="https://cloud.githubusercontent.com/assets/167831/20497748/41aec280-afdf-11e6-9378-f05964955181.gif">
</td>
</tr>
</table>

**Comment by eg271** [comment]
Ok, I've now solved this.  Needed to create a brand new Cordova project in both cases and add everything from scratch.  This seems to have solved the crash issue as well - or at least I haven't been able to recreate it since.

Thanks for your help.

**Comment by wf9a5m75** [comment]
I haven't experienced with any trouble from v1 to v2 (since I know everything),
but some people face similar problem when they port their code from v1 to v2.
In that case, creating a new project is better solution.

**Comment by wf9a5m75** [comment]
@eg271 ping

**Comment by eg271** [comment]
All working ok now after starting a fresh Cordova project so this issue seems resolved
