### ISSUE TITLE
blank map on ios

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/v2.0-demo#2]
im testing this beta plugin but i have this issue blank map, when you said that we have to set the apikey where are the files? the config for android and ios is the same?

![img_0056](https://cloud.githubusercontent.com/assets/17621449/19088868/b6cefeda-8a3d-11e6-8100-0d7b3513cd3e.jpg)

**Comment by wf9a5m75** [comment]
API key for Android and iOS are different.

**Comment by dsemerida** [comment]
Yeah i know , but i wanna know where is the files on ios that i need to set the key for resolve the blank map on my ios

**Comment by wf9a5m75** [comment]
Rewrite the config.xml file directory **before** execute `cordova prepare`.

Otherwise, you need to replace these files by your hand.
- config.xml
- platforms/ios/MultipleMaps/MultipleMaps-Info.plist
- plugins/fetch.json
- plugins/ios.json

**Comment by wf9a5m75** [comment]
Please follow the instruction.
https://github.com/mapsplugin/v2.0-demo/blob/master/README.md#build-the-demo-app
