### ISSUE TITLE
Blank maps

### ISSUE THREAD

**Issue by flipjack** [mapsplugin/v2.0-demo#21]
i have this error in console 

<img width="349" alt="screen shot 2016-11-24 at 19 08 20" src="https://cloud.githubusercontent.com/assets/4236722/20611955/6835f79c-b279-11e6-8ab9-91f19597073b.png">

![img_0057](https://cloud.githubusercontent.com/assets/4236722/20612050/2035dcee-b27b-11e6-9f71-dcf26a61aa09.PNG)

**Comment by wf9a5m75** [comment]
The error message is not related with this plugin.
