### ISSUE TITLE
Map show only after an interaction

### ISSUE THREAD

**Issue by sepiropht** [mapsplugin/v2.0-demo#22]
I'm just trying to use the plugin with the ionic example conference app.

Everything is working expect that you have to click on map before it appear on the screen . if you don't the map never show by itsef.
[A repo to test](https://github.com/sepiropht/conference-ionic-googlePluginV2)

**Comment by wf9a5m75** [comment]
Ionic starts slow.
In that case, you need to fire the `plugin_touch` event by yourself.

`cordova.fireDocumentEvent('plugin_touch', {});`

More details, read here.

https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F#change-4-save-battery-life

**Comment by sepiropht** [comment]
Ok thanks i will tried that !

**Comment by sepiropht** [comment]
I have one more question,  i know that touch event not work like you mention [there](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/844#issuecomment-200467799)
 
But event like MAP.CLICK and MAP_LONG_Clik or CAMERA_MOVE should work no ?
I tried all this the repo  example and put console.log() in their callback , and it don't seems to work

**Comment by wf9a5m75** [comment]
MAP_CLICK
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Map/MAP_CLICK.html

MAP_LONG_CLICK
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Map/MAP_LONG_CLICK.html

CAMERA_MOVE_START / CAMERA_MOVE / CAMERA_MOVE_START events
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Map/CAMERA_EVENTS.html

**Comment by wf9a5m75** [comment]
@sepiropht ping

**Comment by sepiropht** [comment]
Not tested yet but thanks, you can close the issue
