### ISSUE TITLE
NSGenericException error

### ISSUE THREAD

**Issue by banterstudios** [mapsplugin/v2.0-demo#23]
I'm getting an NSGenericException error whilst moving DOM elements over the map, it happens every so often I can't show the source code of the app but i'll try and create a separate project and try and reproduce the bug.

But for now this is the error returned:

Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x600000659830> was mutated while being enumerated.'

**Comment by wf9a5m75** [comment]
I didn't consider such a case for v2. The plugin might be crashed easily.
Please provide the example project.

**Comment by wf9a5m75** [comment]
@banterstudios ping

**Comment by banterstudios** [comment]
Sorry, been really busy I haven't forgotten, will do this as soon as I can.

**Comment by DaDanny** [comment]
Hey, has anyone had any luck with this issue? I've been experiencing it quite a bit on iOS and haven't had a chance to dive into it. I am going to do that this week, and confident I can solve it, but I'd love to know if someone else fixed it already.

Thanks.

**Comment by wf9a5m75** [comment]
@DaDanny Please provide a simple example that reproduce the issue 100%. Note that please include all files, instruction how to build (if you use cordova wrapper such as ionic), data. And please share the all project files using git repository (github or bitbucket)

**Comment by DaDanny** [comment]
@wf9a5m75 Got it, and will do. I am tied up for the first part of this week, but I plan on tackling it later this week and will send some sample code.

Also, I just wanted to say you have done an amazing job with this, and you're incredibly talented. Nice work :)

**Comment by wf9a5m75** [comment]
Hi guys, thank you for using the plugin v2.

I fixed some bugs that might be related with this issue.
Please reinstall the plugin with `--nofetch` option.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/Installation/README.md#installation


If you still face any issues, please file another issue. Thanks.
