### ISSUE TITLE
Using one instance of map [Question]

### ISSUE THREAD

**Issue by starostin** [mapsplugin/v2.0-demo#25]
Hi. First of all thank you for your job. This plugin is very helpful for me and my project. Now I try to update plugin to 2 version. And I have an issue. In my app I using 1 instance of map. So, when app start, I create map and write it in window
```
 window.mapObject = plugin.google.maps.Map.getMap({
                        'mapType': plugin.google.maps.MapTypeId[mapType],
                        'controls': {
                            'compass': false,
                            'myLocationButton': false,
                            'indoorPicker': false,
                            'zoom': false
                        },
                        'gestures': {
                            'scroll': true,
                            'tilt': false,
                            'rotate': true,
                            'zoom': true
                        }
                    });
```

Than, when I open page with map I use setDiv method. 
```
window.mapObject.setDiv(document.querySelector('#map_canvas'));
```

Than I open another page, and go back to page with map. And make setDiv method again.
This worked with 1.4.0 version. But with 2 version app crashes. 
So, what I am doing wrong? Or you need more info?

**Comment by wf9a5m75** [comment]
I think you need to `window.mapObject.setDiv(null)` before changing to another page.

**Comment by starostin** [comment]
Yes, you are right. Now it works fine for  me. But I noticed one issue with that. When I call setDiv method many times, class " _gmaps_cdv_" always added. And than I have http://prntscr.com/dj8h1q.  For fixing that, I have changed setDiv method in Map.js.
So, you had
`} else if (div.className && div.className.indexOf('_gmaps_cdv_') != -1) {`
And I changed it to 
`} else if (div.className && div.className.indexOf('_gmaps_cdv_') === -1) {`

**Comment by wf9a5m75** [comment]
Oh, I missed your reply... Sorry and thank you for your advice.

I fixed it.
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/3048b6c362814ad16781af2066342703f1028225
