### ISSUE TITLE
iOS app crashes when clicking multiple times

### ISSUE THREAD

**Issue by davidgamarra** [mapsplugin/v2.0-demo#28]
Firstly I would like to thank the work done in version 2, since there were several improvements respect to version 1.
However I'm getting the following  failure in the app I'm developing in iOS (it works perfectly in Android):

*** Terminating app due to uncaught exception 'NSGenericException',
reason: '*** Collection <__NSDictionaryM: 0x18253ff0> was mutated while being enumerated.’

If a user performs many clicks in a short amount of time, the app crashes and it produces this error. I don't know if this is relevant, but I'm using Fastclick in the app, so maybe the error is caused because of this. I'm sorry for not being able to offer more info about this.

**Comment by wf9a5m75** [comment]
Could you make an example that reproduce the issue 100% ? Then please share it on github or bitbucket.

**Comment by davidgamarra** [comment]
Ok, I'm a little busy right now, but as soon as I can I will create a clean project and I will try to reproduce the error and then share it with you. The project I'm working right now is based on Cordova + onsen.ui + angularjs. Anyways, I'm going to try to simplify all dependencies and reproduce the error, and then share it with you.

**Comment by davidgamarra** [comment]
Hi Mashashi,

I downloaded the version 2 demo in order to try to reproduce the same error that occurs in my application. I managed to reproduce it although it's a little bit harder to reproduce in my app, since I get the error just by doing some clicks, but in your demo app I had to do more and faster clicks, then the app freezes and I get the error.

In order to reproduce the error I entered into the demo's "Map" section, in "getMap ()", and once the maps are loaded, in the first map if you do a lot of clicks you get the zoom effect, but sometimes that error is produced and the app closes.

I hope this helps you to debug the error and get a solution. If you need something else please let me know.

**Comment by wf9a5m75** [comment]
The plugin is not for design for multiple clicking so faster.

**Comment by davidgamarra** [comment]
Ok, don't worry.
It's just that the users that are using my app are having a bad user experience with the map, since for them the regular behaviour of the map is zoom when double tapping. But then, if the users tap too fast and too many times, the app crashes, If you know a way to avoid this issue, even by using Javascript, I would be more than thankful.
I tried to handle the map's DOM events in order to control the number of taps performed using an interval and block them when there are too many, but I haven't managed to capture the map's event using Javascript.
Thanks.

**Comment by DaDanny** [comment]
So I've been encountering this as well. I did a ton of digging, and while I don't have a solid solution or anything close to a PR ready to go, I believe I was able to trace down what happens and a very temporary solution.


In MyPluginLayer.m, around line 341, you should see the start of a for loop

`for (NSString *domId in self.pluginScrollView.debugView.HTMLNodes) {
`

All I did for now is wrap that for loop in a try... catch block by typing @try and then throwing an exception, which I do nothing will.


Unfortunately, I am not able to track down exactly what is causing the exception, I think I'm close, but this is the only thing I could get to work. 

I will continue investigating this and hope I can put together a solid solution and PR, but for now, that's the best solution I have.

**Comment by davidgamarra** [comment]
Thanks DaDanny, it works like a charm, its not the best solution, but it solves my problem. I'm not familiarized with Objective-C and and I'm having a lot of difficulties to find the error, so it's enough for me.
