### ISSUE TITLE
The showDialog function is available in this version?

### ISSUE THREAD

**Issue by manufuentescr** [mapsplugin/v2.0-demo#29]
Hi, I try to display the map in fullscreen, but when I call the map.showDialog() function I get the following error

"Uncaught TypeError: map.showDialog is not a function"

The option of full screen in this version is available?

**Comment by wf9a5m75** [comment]
The `showDialog()` method is not implemented.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Migrate-from-v1-to-v2#deprecated--not-ready-yet

**Comment by manufuentescr** [comment]
Thanks
