### ISSUE TITLE
Android Crashing

### ISSUE THREAD

**Issue by allurco** [mapsplugin/v2.0-demo#30]
This happened just after the installation, it builds well, but then it crashes, Can you help? 

Cordova Android 6.1.2

Here is the debug info:

`
03-05 14:03:39.500: E/AndroidRuntime(28858): FATAL EXCEPTION: main
03-05 14:03:39.500: E/AndroidRuntime(28858): Process: global.followme.geoapp, PID: 28858
03-05 14:03:39.500: E/AndroidRuntime(28858): java.lang.NoSuchMethodError: No static method zzA(Ljava/lang/Object;)Lcom/google/android/gms/dynamic/zzd; in class Lcom/google/android/gms/dynamic/zze; or its super classes (declaration of 'com.google.android.gms.dynamic.zze' appears in /data/app/global.followme.geoapp-1/base.apk)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at com.google.android.gms.maps.internal.zzai.zzbq(Unknown Source)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at plugin.google.maps.CordovaGoogleMaps$1.run(CordovaGoogleMaps.java:238)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at android.app.Activity.runOnUiThread(Activity.java:5575)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at plugin.google.maps.CordovaGoogleMaps.initialize(CordovaGoogleMaps.java:104)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at org.apache.cordova.PluginManager.init(PluginManager.java:86)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:115)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at global.followme.geoapp.MainActivity.onCreate(MainActivity.java:39)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at android.app.Activity.performCreate(Activity.java:6289)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at android.os.Handler.dispatchMessage(Handler.java:102)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at android.os.Looper.loop(Looper.java:145)
03-05 14:03:39.500: E/AndroidRuntime(28858): 	at android.app.ActivityThread.main(ActivityThread.java:5951)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at java.lang.reflect.Method.invoke(Native Method)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at java.lang.reflect.Method.invoke(Method.java:372)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)

03-05 14:03:39.500: E/AndroidRuntime(28858): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
`

**Comment by wf9a5m75** [comment]
Your google play services library is old

**Comment by allurco** [comment]
That is what I have in my build.gradle

```
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    compile "com.google.android.gms:play-services-maps:10.0.0"
    compile "com.google.android.gms:play-services-location:10.0.0"
    compile "com.android.support:support-v13:23+"
    compile "com.google.android.gms:play-services-gcm:9.8+"
    compile "me.leolin:ShortcutBadger:1.1.11@aar"
    // SUB-PROJECT DEPENDENCIES END
}
```

Any tip to solve this problem?

**Comment by allurco** [comment]
Got it: Changed the project.properties to:

```
cordova.gradle.include.1=com.transistorsoft.cordova.background-geolocation/geoapp-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-maps:10.+
cordova.system.library.2=com.google.android.gms:play-services-location:10.+
cordova.gradle.include.2=phonegap-plugin-push/geoapp-push.gradle
cordova.system.library.3=com.android.support:support-v13:23+
cordova.system.library.4=com.google.android.gms:play-services-gcm:10.+
cordova.system.library.5=me.leolin:ShortcutBadger:1.1.11@aar
```
