### ISSUE TITLE
how to remove (clear) events

### ISSUE THREAD

**Issue by manufuentescr** [mapsplugin/v2.0-demo#31]
hi, i need clear the map click event . i need variated  the function when click map  , but the "map click" event ejecute the functions established previously.

Example :

```javascript

	window.map.on(plugin.google.maps.event.MAP_CLICK, function(latLng) 
	{
		console.log("map click");		
	});
```
output :  "map clik" in console

i set the event again

```javascript

	window.map.on(plugin.google.maps.event.MAP_CLICK, function(latLng) 
	{
		alert ("map click");		
	});
```
output :  "map clik" in console and alert "map click"  , whe should show only the alert.

exist some function to clear event , exept map.remove() ?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/BaseClass#addeventlistener-and-removeeventlistener

**Comment by manufuentescr** [comment]
its works.

Thanks.
