### ISSUE TITLE
On the road to support Crosswalk

### ISSUE THREAD

**Issue by PapyElGringo** [mapsplugin/v2.0-demo#33]
Hi guys, Im gonna try to make it work with Crosswalk at least partially for what I need.

Feel free to share your issues here.

**Comment by wf9a5m75** [comment]
Add the below two lines to config.xml

```xml
    <preference name="xwalkZOrderOnTop" value="true" />
    <preference name="BackgroundColor" value="0" />
```

Then the plugin works with CrossWalk.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/Installation/crosswalk/README.md
