### ISSUE TITLE
The demo apk and screen shot image are all borken

### ISSUE THREAD

**Issue by tienw** [mapsplugin/v2.0-demo#34]
as title. Anyone?

**Comment by wf9a5m75** [comment]
I know. I haven't fixed them yet. sorry

**Comment by tienw** [comment]
thank you for quick reply, I really need the apk uploaded so I can see how it goes for my needs.

**Comment by wf9a5m75** [comment]
https://www.dropbox.com/s/u5ekxc1lls0j7ry/cordova-googlemaps-v2-demo_02.apk?dl=0

**Comment by wf9a5m75** [comment]
fixed.
