### ISSUE TITLE
Blank screen using version 2.0 with Ionic 3.

### ISSUE THREAD

**Issue by SKempin** [mapsplugin/v2.0-demo#35]
I'm getting a blank white screen when trying to load the map with Ionic 3, is this supported?

**Comment by wf9a5m75** [comment]
I've never used ionic. So I've never tested on ionic.

Please make a simple example that reproduce your issue 100%, then put it on a github repository with full code.

Don't share your full code of your app.

**Comment by wf9a5m75** [comment]
Please follow this page.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/For-ionic2-users/README.md
