### ISSUE TITLE
[iOS] method not found: create in PluginKmlOverlay class

### ISSUE THREAD

**Issue by brunosouza** [mapsplugin/v2.0-demo#36]
Hello folks, i'm trying to add a kmlOverlay but got stuck whit this error:

>2017-04-24 15:04:26.375 MyAqpp[6184:1676926] method not found: create in PluginKmlOverlay class

I've updated the maps plugin this afternoon, and the error only happens on iOS, Android works fine.

Code to add the kmlOverlay
```javascript
function onMapReady() {
	angular.forEach(trilhas,function(v,k){
		markersData.push({'thumb':v.imageUrl,'trilhaID':v.id,'nivel':v.dificuldade,'distancia':v.distancia,'likes':v.like,'duracao':v.duracao,'parque':v.unidadeconservacao[0].nome,'nome-trilha':v.nome,'position': new plugin.google.maps.LatLng(v.latitude,v.longitude),'icon':{'url':'http://etrilhas.alfaia.co/transcarioca/marker.png','size':{width:32,height:32}}})
	})

	markersOriginais = markersData;

	map.setMapTypeId(plugin.google.maps.MapTypeId.ROADMAP);
	map.moveCamera({
		'target':new plugin.google.maps.LatLng(-22.932425,-43.443078),
		'zoom':10
	});

	map.addKmlOverlay({
		'url': "https://etrilhas.com.br/transcarioca/transcarioca-principal.kml"
	}, function(kmlOverlay) {
		$ionicLoading.hide();
	});

	addMarkers(markersData, function(markers) {});
}
```

Plugins i'm using 
>com.googlemaps.ios 2.2.0 "Google Maps SDK for iOS"
cordova-plugin-camera 2.4.0 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.6 "Console"
cordova-plugin-contacts 2.3.0 "Contacts"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-dialogs 1.3.2 "Notification"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-file 4.3.2 "File"
cordova-plugin-file-transfer 1.6.2 "File Transfer"
cordova-plugin-google-analytics 1.7.5 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.0.0-beta "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.6 "SocialSharing"
cordova-plugin-x-toast 2.6.0 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by wf9a5m75** [comment]
cordova-plugin-googlemaps 2.0.0-beta does not have the "addKmlOverlay" method yet.

**Comment by wf9a5m75** [comment]
I mean the addKmlOverlay is not implemented completely yet. Still working on it.

**Comment by brunosouza** [comment]
oh, sorry fot bother you. shame on me 😞
