### ISSUE TITLE
Multiple Markers still makes the map laggy

### ISSUE THREAD

**Issue by adappter** [mapsplugin/v2.0-demo#38]
Hello I have installed the current version of your plugin within Ionic 3.

I have about 700+ Markers which I have to render. I read already this Issue:
[#835](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/835)

My Code looks like this:
```
markersAdd() {
   let array = new plugin.google.maps.BaseArrayClass(this.reports);
    array.map( report => {
      this.map.addMarker({
        'title': report.description,
        'position': new plugin.google.maps.LatLng(report.lat, report.lng),
        'place_id': report.id,
        'icon': {
          'url':  report.pinImage,
          'anchor': [16, 20],
          'size': {
            width: 32,
            height: 41
          }
        },
        'place': report,
        'visible': true,
      }, marker => {
        marker.addEventListener(plugin.google.maps.event.MARKER_CLICK, () => {
          marker.showInfoWindow();
        });
      });
    }, markers => {
      console.log(markers);
    });
}
```

Is this issue still known and we have to wait for clustering? Or am I doing something wrong?

Thank you so far.

**Comment by wf9a5m75** [comment]
As I announced here,  I have been developing the cluster feature.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1006#issuecomment-298133452

**Comment by wf9a5m75** [comment]
I read your code, and I noticed you misunderstand this plugin.

The method `map.addXXXXX` (ie, `map.addMarker()` etc..) takes a callback function,
which means the method returns the result later. It means the method is the same as `setTimeout()`

```js
console.log("--->before addMarker");

map.addMarker(options, function() {
    console.log("--->addMarker was finished");
});

console.log("--->after addMarker");
```

The above code outputs 
```
--->before addMarker
--->after addMarker
--->addMarker was finished
```

------

So executing `map.addMarker` with `array.map`, means similar to like this:

```js
var markers = [];
reports.map(function(report) {

   map.addMarker({...}, function(marker) {
     markers.push(marker);
   });
});

console.log(markers); // <-- of course, empty
```

------------

So what is the solution. Use `BaseArrayClass`.

You can write your code like this:

```js
  var reportList = new plugin.google.maps.BaseArrayClass(reports);
  reportList.map(function(report, cb) {
    map.addMarker({
       ....
    }, cb);
  }, function(markers) {
     console.log(markers);
  });
```

For more details, please read this page.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseArrayClass/README.md

**Comment by adappter** [comment]
Hey @wf9a5m75,
I already use the BaseArrayClass as you will see the first line after method declaration.

**Comment by wf9a5m75** [comment]
Oh, I see. i missed it.
Thrn what's the problem? Slow? Of course, 700+ markers take kind of long time.

The marker clustering? Not available right now.

**Comment by adappter** [comment]
The problem ist not the time it takes.
I'm waiting till every marker is loaded. After that, when I'm scrolling the map, it is very laggy.

**Comment by wf9a5m75** [comment]
Many markers uses also lots of memory. That's why, and that's not bug.
