### ISSUE TITLE
HtmlInfoWindow with Ionic Template

### ISSUE THREAD

**Issue by adappter** [mapsplugin/v2.0-demo#39]
Hey there,

I'm using the HtmlInfoWindow with Ionic Template. 
The html is rendered correctly but somehow the data binding doesn't work. 
Is there a solution for this kind of problem? Or are there alternatives?
What I want is to show some informations and a button calling a function.

```
var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();
    var html =
      `
      <ion-avatar item-left>
      <img src="{{selectedReport.pinImage}}"/>
        </ion-avatar>
        <h2>{{selectedReport.typeString}}</h2>
    </ion-item>

    <ion-card-content>
    <ion-item>
    <ion-label text-wrap>{{selectedReport.description}}</ion-label>
    </ion-item>
    <ion-item>
    <ion-label text-wrap>{{selectedReport.address}}</ion-label>
    </ion-item>
    </ion-card-content>
    </ion-card>`
    htmlInfoWindow.setContent(html);
```
I know that the readme use arrray and join it. But I tried this also.

**Comment by wf9a5m75** [comment]
This plugin just inserts the strings to an internal div.
That's why ionic data binding does not work.

**Comment by wf9a5m75** [comment]
Unfortunately I'm not familiar with ionic at all. Please ask at the ionic forum.

**Comment by adappter** [comment]
Ok what about like this:
When I'm clicking the marker, I should get the correct report (maybe via an index?). 
After I get the correct report, another function will be called and a custom view will rendered inside my app.

Is it possible to get the correct report and call a function when clicking a marker?

**Comment by wf9a5m75** [comment]
Please ask the rendering questions at the ionic forum. I have no answer.

And getting your data(report) is easy.

```js

map.addMarker({
  ...
  report: report
}, function(marker) {
  marker.on(plugin.google.maps.event.MARKER_CLICK, onMarkerClick);
});

function onMarkerClick () {
  var marker = this;
  var report =marker.get("report");
}
```

Please read more the documents, that saves your time.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md
