### ISSUE TITLE
ERROR FOR COMPILATION

### ISSUE THREAD

**Issue by morellato** [mapsplugin/v2.0-demo#4]
Please, can you help me ?
When compiling the demo, the following error appears:

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any matches for com.google.android.gms:play-services-maps:+ as no versions of com.google.android.gms:play-services-maps are availa
ble.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-maps/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-maps/
         https://jcenter.bintray.com/com/google/android/gms/play-services-maps/maven-metadata.xml
         https://jcenter.bintray.com/com/google/android/gms/play-services-maps/
         file:/C:/Users/Wanderson Aequus/AppData/Local/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/maven
-metadata.xml
         file:/C:/Users/Wanderson Aequus/AppData/Local/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/
     Required by:
         :android:unspecified
   > Could not find any matches for com.google.android.gms:play-services-location:+ as no versions of com.google.android.gms:play-services-location ar
e available.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-location/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-location/
         https://jcenter.bintray.com/com/google/android/gms/play-services-location/maven-metadata.xml
         https://jcenter.bintray.com/com/google/android/gms/play-services-location/
         file:/C:/Users/Wanderson Aequus/AppData/Local/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-location/m
aven-metadata.xml
         file:/C:/Users/Wanderson Aequus/AppData/Local/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-location/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by wf9a5m75** [comment]
It seems your compiler does not accept `<framework src="com.google.android.gms:play-services-maps:+" />`

**Comment by wf9a5m75** [comment]
I updated the plugin.xml of the multiple_maps branch.
Uninstall the current plugin, then reinstall it.

**Comment by ZiFFeL1992** [comment]
You should update Play Services from Android SDK Manager, run into this issue this morning.

**Comment by morellato** [comment]
wf9a5m75O, plugin que voce fala para instalar novamente é o cordova-plugi-googlemaps ?
Se foir isso, eu já tentei e apresentou o mesmo erro.

**Comment by Hirbod** [comment]
@morellato do you really think that we can understand portuguese?

**Comment by morellato** [comment]
wf9a5m75O ..sorry..now in english: The plugin that you say to install again is the cordova-plugin-googlemaps?
If foir this, I've tried and had the same error.
tks

**Comment by wf9a5m75** [comment]
I think you don't installl the Google Play Services into your pc.
Otherwise please post the error log.

**Comment by ZiFFeL1992** [comment]
Read what I wrote to you please @morellato .

You need to install them from Android SDK Manager. Seems like we can't download them when we need it, we should have them locally.
