### ISSUE TITLE
INFO_LONG_CLICK

### ISSUE THREAD

**Issue by Usmaaan** [mapsplugin/v2.0-demo#43]
INFO_LONG_CLICK is not working, and how can i enable user to edit the marker title, any help/idea/suggestion ?

**Comment by wf9a5m75** [comment]
How did you write your code?

**Comment by Usmaaan** [comment]
i have used also used other events INFO_CLICK , MARKER_CLICK , they are working fine but not the following one. Can you tell what is the problem ?

marker.on(plugin.google.maps.event.INFO_LONG_CLICK, function() {
                                   marker.remove();
                                 });

**Comment by wf9a5m75** [comment]
Do you use the plugin v1 or v2?

**Comment by Usmaaan** [comment]
V2

**Comment by Usmaaan** [comment]
i saw your earlier posts and now updating the plugin

**Comment by wf9a5m75** [comment]
>now updating the plugin

Updated to v2.0?

**Comment by wf9a5m75** [comment]
Please share your project files on github or bitbacket.

How and why?
#1479

**Comment by Usmaaan** [comment]
hi @wf9a5m75 , i have uninstalled the previous version 1.4.0 and trying to install the 2.0 now i getting this Repository "https://github.com/mapsplugin/cordova-plugin-googlemaps.git" checked
 out to git ref "master". and it downloads the previous version 1.4.0

**Comment by Usmaaan** [comment]
i have fixed the problem, and its working fine Big thanks to you :-)
