### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by rlaurente** [mapsplugin/v2.0-demo#50]
![screen shot 2017-09-04 at 8 50 26 pm](https://user-images.githubusercontent.com/1804380/30027310-e68cfaaa-91b2-11e7-9cb0-7c22b5413d47.png)
I see this error in my console

"Failed to restore plugin "cordova-plugin-googlemaps" from config.xml. You might need to try adding it again. Error: Error: Invalid package.json"

It seems you forgot to add the package.json

**Comment by wf9a5m75** [comment]
The package.json file will be generated if there is no existed.
You can ignore the error.

Since the npm installs packages based on package.json if the file is existed, but it is for my environment, not for other people, like windows or linux.
That's why I don't include the file.
