### ISSUE TITLE
No Map on Demo

### ISSUE THREAD

**Issue by HeliosMagin** [mapsplugin/v2.0-demo#51]
Hello, 

I'm trying to do the Demo, but I'm hitting a wall, I appreciate any help or advice, these are the steps I've done so far:

* Installed phonegap cli v7.1.1
* Cloned this repo
* Followed steps of readme to build the demo app [https://github.com/mapsplugin/v2.0-demo#how-to-build-the-demo-app](url)
* Executed: `cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."` (with my console values)
* Added android and IOs platform
```
phonegap platform list
android 6.2.3
browser 5.0.1
ios 4.4.0
```
* Verified plugin list:
```
phonegap plugin list
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4 "Cordova WKWebView Engine"
```
* Installed phonegap developer from the playstore on an Android phone (v5.1.1)
* Executed: `phonegap serve` and connected on the phonegap developer app on android to the URL
* Program runs fine but no map shows :/
* Not sure if related, but on the console I get warnings:
```
[phonegap] [console.warn] Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src 'self' gap: * ws: https://ssl.gstatic.com;script-src 'self' data: https://ssl.gstatic.com 'unsafe-eval' * 'unsafe-inline' blob:;object-src *;style-src 'self' data: 'unsafe-inline' * blob:;img-src 'self' data: * content:;media-src 'self' data:;font-src 'self' data:;connect-src *;">
``` 

I get several of these over and over, I can figure it's related to what is on the meta tags on the html head of pages. The app navigates well, but all instances where a map would show it's blank. Similar to #21 

No changes have been done to the code.

For the google console I enabled both ` Google Maps Android API` and `Google Maps SDK for iOS` but otherwise the API keys are unrestricted.

Appreciate any guidance, thanks

**Comment by wf9a5m75** [comment]
The `serve` command is not supposed. This plugin works on real devices

**Comment by HeliosMagin** [comment]
Oh, I think I understand, sorry for the confusion, I was under the impression that if I used the phonegap developer app on the phone it counted as using Android.

I will look into an alternative, thanks
